version: '3.8'

services:
  mathflat-app:
    container_name: mathflat-app
    build: .
    volumes:
      - ./temp_imgs:/app/temp_imgs # 임시 이미지 저장소 공유
    restart: always
    expose:
      - "8000"
    networks:
      - proxy

networks:
  proxy:
    external: true
